In [1]:
#import the pyplot and wavfile modules 

import matplotlib.pyplot as plot
from scipy.io import wavfile
import librosa
import numpy as np
from numpy import load
# Read the wav file (mono)

samplingFrequency, signalData = wavfile.read('ae5f103b-5fee-442f-bb1b-d9d0570c46ab-1431533857965-1.7-m-26-bp.wav')

# Plot the signal read from wav file

plot.subplot(211)
plot.title('Spectrogram of a .wav file of baby crying')
plot.plot(signalData)
plot.xlabel('Sample')
plot.ylabel('Amplitude')



plot.subplot(212)
plot.specgram(signalData,Fs=samplingFrequency)
plot.xlabel('Time')
plot.ylabel('Frequency (Hz)')

plot.show()

data = np.load('ae5f103b-5fee-442f-bb1b-d9d0570c46ab-1431533857965-1.7-m-26-bp.wav.npz')

melgram = data ['melgram']

melgram = np.squeeze(melgram)

plot.plot(melgram)
plot.ylabel('Mel Scale')
plot.xlabel('Frequency')
plot.show()

/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_axes.py:7585: RuntimeWarning: divide by zero encountered in log10
  Z = 10. * np.log10(spec)


<Figure size 640x480 with 2 Axes>

<Figure size 640x480 with 1 Axes>

In [6]:
#  This commented section shows melgram array
lst = data.files

print(melgram)





[[-32.78 -32.78 -32.78 ... -32.78 -32.78 -32.78]
 [-32.78 -32.78 -32.78 ... -32.78 -32.78 -32.78]
 [-32.78 -32.78 -32.78 ... -32.78 -32.78 -32.78]
 ...
 [-32.78 -32.78 -32.78 ... -32.78 -32.78 -32.78]
 [-32.78 -32.78 -32.78 ... -32.78 -32.78 -32.78]
 [-32.78 -32.78 -32.78 ... -32.78 -32.78 -32.78]]
